config/routes.rb
Bountyboard::Application.routes.draw do

  root :to => 'Bounties#index'

  resources :artists
  resources :bounties, shallow: true do
    resources :comments
    member do
      get 'complete'
    end
  end

  # these resources are managed automatically by the system, so we don't need
  # user-accessible index, new, or edit forms
  resources :candidacies, :except => [:index, :new, :edit]
  resources :votes, :except => [:index, :new, :edit]
  resources :favorites, :except => [:index, :new, :edit]

  resources :users, :except => [:index] # forbid listing users

  # authentication routes
  match '/auth/:provider/callback', to: 'Sessions#create'
  match '/sign_out', to: 'Sessions#destroy', via: [ :delete, :post ]
  match '/auth/failure', to: 'Sessions#auth_failure'
end

app/models/artist.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  email              :citext           not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  deleted_at         :datetime
#  type               :string(255)
#  bio                :text             default(""), not null
#  bounty_rules       :text             default(""), not null
#  approved           :boolean          default(FALSE), not null
#  admin              :boolean          default(FALSE), not null
#  badge_file_name    :string(255)
#  badge_content_type :string(255)
#  badge_file_size    :integer
#  badge_updated_at   :datetime
#

class Artist < User

  # Relationships ==============================================================
  has_many :candidacies, :inverse_of => :artist
  has_many :bounties, :through => :candidacies

  # Paperclip gem.
  has_attached_file :badge, :styles => { :standard => "280x200>",
    :default_url => "/images/Badge.png" }

  # Validations ================================================================
  validates :bio, presence: true
  validates :bounty_rules, presence: true
  validates :approved, :inclusion => {:in => [true, false]}

  # The "name" property is optional for users but required for artists
  validates :name, presence: true

  acts_as_paranoid


  # Methods ====================================================================

  # parses the markdown in this artist's bio property into safe HTML so that it
  # can be used directly in a view
  def bio_to_html
    parse_markdown(self.bio)
  end

  # parses the markdown in this artist's bounty_rules property into safe HTML
  # so that it can be used directly in a view
  def bounty_rules_to_html
    parse_markdown(self.bounty_rules)
  end


  # Artist query filters =======================================================
  #
  # Use these to get specific subsets of bounties. These
  # methods are chainable.
  class << self
    def available()
      where( :approved => true )
    end
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  include FiltersHelper

  skip_before_filter :require_login, :only => [:index, :show]

  # the maximum number of bounties that can be displayed in each
  # section of the artist dashboard
  def self.BOUNTIES_PER_SECTION
    20
  end

  # Display a list of all artists in the system, with links to see their
  # individual profiles.
  def index
    # TODO show inactive artists?
    @artists = Artist.where("approved = ?", true).order("name")
  end

  # Display an individual artist's profile.
  def show
    # TODO show inactive artists?
    if Artist.exists?(:id => params[:id])
      @artist = Artist.find(params[:id])

      @owner_artist_visiting = (current_user == @artist)
      @admin_visiting = current_user && current_user.admin?

      # if the user has uploaded an image then use it, otherwise use a
      # placeholder
      if @artist.badge.file?
        @badge_url = @artist.badge.url
      else
        @badge_url = 'Badge.png'
      end

    # now use the filter system to get a list of accepted and completed
    # bounties to display

    @completed_bounties = apply_filters(
      Bounty,
      { artist_portfolio: @artist.name }
    ).last(ArtistsController.BOUNTIES_PER_SECTION).sort!

    @accepted_bounties = apply_filters(
      Bounty,
      { artist_workload: @artist.name }
    ).last(ArtistsController.BOUNTIES_PER_SECTION).sort!
    else
      flash[:error] = "That artist does not exist."
      if request.env['HTTP_REFERER']
        redirect_to :back
      else
        redirect_to root_url
      end
    end
  end

  # Display the form to create a new artist. Only admins may perform this
  # action.
  def new
    if current_user.admin?
      @artist = Artist.new
    else
      flash[:error] = "Only administrators can create new artists."
      if request.env['HTTP_REFERER']
        redirect_to :back
      else
        redirect_to root_url
      end
    end
  end

  # Create a new artist. Only admins may perform this action.
  def create
    unless current_user.admin?
      flash[:error] = "Only administrators can create new artists."
      if request.env['HTTP_REFERER']
        redirect_to :back
      else
        redirect_to root_url
      end
      return
    end

    #TODO Figure out how approved fits into our workflow.
    params[:artist][:approved] = true

    @artist = Artist.new(artist_create_params)
    if @artist.save
      flash[:notice] = "Artist created successfully!"
      redirect_to artist_path(@artist)
    else
      flash[:error] = "Error saving artist."
      render 'new'
    end
  end

  # Display the edit form for the currently logged in artist or for an
  # administrator.
  def edit
    if Artist.exists?(:id => params[:id])
      @artist = Artist.find(params[:id])
      unless (@artist == current_user || current_user.admin?)
        flash[:error] = "You are not authorized to edit this artist."
        if request.env['HTTP_REFERER']
          redirect_to :back
        else
          redirect_to root_url
        end
      end
    else
      flash[:error] = "That artist does not exist."
      if request.env['HTTP_REFERER']
        redirect_to :back
      else
        redirect_to root_url
      end
    end
  end

  # Update the currently logged in artist. Admins are allowed to update artist
  # properties.
  def update
    if Artist.exists?(:id => params[:id])
      @artist = Artist.find(params[:id])
      unless (@artist == current_user || current_user.admin?)
        flash[:error] = "You are not authorized to edit this artist."
        if request.env['HTTP_REFERER']
          redirect_to :back
        else
          redirect_to root_url
        end
        return
      end

      if @artist.update_attributes(artist_update_params)
        flash[:notice] = "Artist updated!"
        redirect_to artist_path(@artist)
      else
        flash[:error] = "Error updating artist."
        if request.env['HTTP_REFERER']
          redirect_to :back
        else
          redirect_to root_url
        end
      end
    else
      flash[:error] = "That artist does not exist."
      if request.env['HTTP_REFERER']
        redirect_to :back
      else
        redirect_to root_url
      end
    end
  end

  # Artists are never hard-deleted. Instead, a "deleted_at" property is set,
  # preventing an artist from participating in the system or being selected for
  # bounties.
  def destroy
    @artist = Artist.find(params[:id])
    if current_user.admin?
      artist_name = @artist.name
      if @artist.destroy
        flash[:notice] = "Artist #{artist_name} is now inactive!"
        redirect_to root_path
      else
        flash[:error] = "Error deactivating artist."
        if request.env['HTTP_REFERER']
          redirect_to :back
        else
          redirect_to root_url
        end
      end
    else
      flash[:error] = "Only administrators can delete artists."
      if request.env['HTTP_REFERER']
        redirect_to :back
      else
        redirect_to root_url
      end
    end
  end

  private

    def artist_create_params
      params.require(:artist).permit(
        :name,
        :email,
        :bio,
        :bounty_rules,
        :approved
      )
    end

    def artist_update_params
      params.require(:artist).permit(
        :name,
        :email,
        :bio,
        :bounty_rules
      )

      # admins alone can approve an artist and can set all other artist
      # properties except the artist's name and email, which can only be
      # changed by the artist
      if current_user.admin?
        params.require(:artist).permit(
          :approved,
          :bio,
          :bounty_rules
        )
      end
    end

end

app/views/artists/edit.html.erb
<div id="form-area">
  <%= render partial: 'shared/artist_error_messages', locals: { artist: @artist } %>
  <%= semantic_form_for @artist do |artist_form| %>
    <%= artist_form.input :name, :required => true %>
    <%= artist_form.input :email, :required => true %>
    <%=
      render(
        :partial => 'shared/markdown_input_field',
        :locals => {
          :model => 'artist',
          :property => 'bio',
          :initial_value => @artist.bio
        }
      )
    %>
    <%=
      render(
        :partial => 'shared/markdown_input_field',
        :locals => {
          :model => 'artist',
          :property => 'bounty_rules',
          :initial_value => @artist.bounty_rules
        }
      )
    %>
    <% if current_user.admin? %>
      <%= artist_form.input :approved%>
    <% end %>
    <div class="control-panel"><%= artist_form.submit :class => "bounty-button submit-button" %><%=   link_to 'Back', artist_path(@artist.id), class: 'bounty-button' %></div>
  <% end %>
</div>

app/views/artists/index.html.erb
<div id="artist-list">
  <ul>
  <% @artists.each do |a| %>
        <li>
        <% if a.badge.file? %>
            <%= link_to image_tag(a.badge.url), artist_path(a.id) %>
            <br>
            <%= a.name %>
        <% else %>
            <%= link_to image_tag('Badge.png'), artist_path(a.id) %>
            <br>
            <%= a.name %>
        <% end %>
        </li>
  <% end %>
  </ul>
</div>

app/views/artists/new.html.erb
<div id="form-area">
    <%= render partial: 'shared/artist_error_messages', locals: { artist: @artist } %>
    <%= semantic_form_for @artist do |artist_form| %>
        <%= artist_form.input :name, :required => true %>
        <%= artist_form.input :email, :required => true %>
        <%=
          render(
            :partial => 'shared/markdown_input_field',
            :locals => {
              :model => 'artist',
              :property => 'bio',
              :initial_value => @artist.bio
            }
          )
        %>
        <%=
          render(
            :partial => 'shared/markdown_input_field',
            :locals => {
              :model => 'artist',
              :property => 'bounty_rules',
              :initial_value => @artist.bounty_rules
            }
          )
        %>
        <div class="control-panel"><%= artist_form.submit :class => "bounty-button submit-button" %><%=   link_to_function 'Back', "history.back()", class: 'bounty-button' %></div>
    <% end %>
</div>

app/views/artists/show.html.erb
<header>
  <%= image_tag(@badge_url, :class => 'artist-badge') %>
  <p class="artist-basic-info">
    <span class="name"><%= @artist.name %></span><br>
    <%= @artist.email %><br>
    Joined : <%= @artist.created_at.to_date.to_s() %><br>
  </p>
</header>

<div class="divider"></div>

<div class="bio-and-rules-container">
  <section class="bio">
    <header class="section-heading">Biography</header>
    <div class="markdown-content-container"><%= @artist.bio_to_html %></div>
  </section>

  <div class="vertical-separator"></div>

  <section class="bounty-rules">
    <header class="section-heading">Rules</header>
    <div class="markdown-content-container"><%= @artist.bounty_rules_to_html %></div>
  </section>
</div>

<div class="divider"></div>

<% unless @accepted_bounties.empty? %>
  <section class="accepted-bounties">
    <header class="section-heading">Currently Working On...</header>
    <%=
      render(
        :partial => 'shared/bounty_list',
        :locals => { :bounties => @accepted_bounties }
      )
    %>
  </section>
  <div class="divider"></div>
<% end %>


<% unless @completed_bounties.empty? %>
  <section class="completed-bounties">
    <header class="section-heading">Portfolio</header>
    <%=
      render(
        :partial => 'shared/bounty_list',
        :locals => { :bounties => @completed_bounties }
      )
    %>
  </section>
  <div class="divider"></div>
<% end %>


<div class="control-panel">
  <%= link_to 'Back', root_path, class: 'bounty-button' %>
  <% if @owner_artist_visiting %>
    <%= link_to 'Update', edit_artist_path(@artist), class: 'bounty-button' %>
    <%= link_to 'Your Dashboard', user_path(@artist), class: 'bounty-button' %>
  <% end %>

  <% if @admin_visiting %>
    <%= link_to 'Update', edit_artist_path(@artist), class: 'bounty-button' %>
    <%= link_to 'Delete', @artist, :confirm => "Are you sure you want to delete #{@artist.name}?", :method => :delete, class: 'bounty-button' %>
    <% if @artist.approved %>
      <%=
        link_to(
          'Un-Approve',
          artist_path(@artist, :artist => {:approved => false}),
          :method => :put,
          :class => 'bounty-button'
        )
      %>
    <% else %>
      <%=
        link_to(
          'Approve',
          artist_path(@artist, :artist => {:approved => true}),
          :method => :put,
          :class => 'bounty-button'
        )
      %>
    <% end %>
  <% end %>
</div>