config/routes.rb
Bountyboard::Application.routes.draw do

  root :to => 'Bounties#index'

  resources :artists
  resources :bounties, shallow: true do
    resources :comments
    member do
      get 'complete'
    end
  end

  # these resources are managed automatically by the system, so we don't need
  # user-accessible index, new, or edit forms
  resources :candidacies, :except => [:index, :new, :edit]
  resources :votes, :except => [:index, :new, :edit]
  resources :favorites, :except => [:index, :new, :edit]

  resources :users, :except => [:index] # forbid listing users

  # authentication routes
  match '/auth/:provider/callback', to: 'Sessions#create'
  match '/sign_out', to: 'Sessions#destroy', via: [ :delete, :post ]
  match '/auth/failure', to: 'Sessions#auth_failure'
end

app/controllers/bounties_controller.rb
class BountiesController < ApplicationController

  include VotesHelper
  include FiltersHelper
  require 'sanitize'

  respond_to :json, :html

  skip_before_filter :require_login, :only => [:index, :show]

  def self.BOUNTIES_PER_PAGE
    40
  end

  # Display a list of all bounties in the system, with links to see their
  # individual bounties.
  def index

    # apply default filters for this page--these filters are mandatory
    @bounties = Bounty
      .page(params[:page]).per(BountiesController.BOUNTIES_PER_PAGE)

    # if no adult filter is specified, use the "kid-friendly" setting; this is
    # done because the default setting "kid-friendly unless viewer involved
    # with bounty" can't easily be represented as a button in the filter UI,
    # is more computationally expensive, and doesn't provide much benefit for
    # the aggregate view of the bounty index page so we simply don't use that
    # setting on this page
    if !params.has_key?(:adult)
      params[:adult] = 'kid-friendly'
    end

    # if the ownership filter was turned on, its value needs to be set to the
    # current user
    if params.has_key?(:own)
      params[:own] = current_user
    end

    # apply filters from the user
    @bounties = apply_filters(@bounties, params)

    respond_with @bounties.all.sort!.reverse!
  end

  # Display an individual bounty.
  def show
    if Bounty.exists?(:id => params[:id])
      @bounty = Bounty.find(params[:id])
      if !@bounty.viewable_by?(current_user)
        flash[:error] = "That bounty is private."
        if request.env['HTTP_REFERER']
          redirect_to :back
        else
          redirect_to root_url
        end
        return
      end
    else
      flash[:error] = "That bounty does not exist."
      if request.env['HTTP_REFERER']
        redirect_to :back
      else
        redirect_to root_url
      end
      return
    end
  end

  # Display the form to create a new bounty. Anyone may perform this action.
  def new
    @bounty = Bounty.new
  end

  # Create a new bounty. Anyone may perform this action.
  def create
    # If no specific artists were selected. Then create a candidacy to all
    # active artists.
    # TODO fix access pattern here
    if !params[:bounty][:artist_ids] || params[:bounty][:artist_ids] == [""]
      params[:bounty][:artist_ids] =
        Artist.available().where('id <> ?', current_user.id).pluck(:id)
    end

    @bounty = Bounty.new(bounty_create_params)
    @bounty.owner = current_user

    if @bounty.save
      flash[:notice] = "Bounty created successfully!"
      redirect_to bounty_path(@bounty)
    else
      flash[:error] = "Error saving bounty."
      render 'new'
    end
  end

  # Display the edit form for the bounty. Artists that are candidates for the
  # bounty may use this for completion of a bounty. Owners of the bounty
  # may edit all other properties.
  def edit
    if Bounty.exists?(:id => params[:id])

      @bounty = Bounty.find(params[:id])

      if !(@bounty.owner == current_user || current_user.admin?)
        flash[:error] = "You are not authorized to edit this bounty."
        if request.env['HTTP_REFERER']
          redirect_to :back
        else
          redirect_to root_url
        end
        return
      end
    else
      flash[:error] = "That bounty does not exist."
      if request.env['HTTP_REFERER']
        redirect_to :back
      else
        redirect_to root_url
      end
    end
  end

  # The complete action displays a special Edit view for the bounty, showing
  # only the artwork properties of the bounty as form fields. Once the artist
  # completes the bounty and submits the artwork, the Bounty#Update action
  # will be invoked on form submission.
  def complete
    if Bounty.exists?(:id => params[:id])

      @bounty = Bounty.find(params[:id])

      if (@bounty.acceptor_candidacy)
          if !(@bounty.acceptor_candidacy.artist == current_user)
          flash[:error] = "You are not authorized to complete this bounty."
          if request.env['HTTP_REFERER']
            redirect_to :back
          else
            redirect_to root_url
          end
          return
        end
      end
    else
      flash[:error] = "That bounty does not exist."
      if request.env['HTTP_REFERER']
        redirect_to :back
      else
        redirect_to root_url
      end
    end
  end

  # Update the bounty. This action updates the bounty model after form
  # submission from either the Edit or Complete view.
  def update
    @bounty = Bounty.find(params[:id])

    unless (@bounty.owner == current_user || @bounty.artists.include?(current_user))
      flash[:error] = "You are not authorized to edit this bounty."
      if request.env['HTTP_REFERER']
        redirect_to :back
      else
        redirect_to root_url
      end
      return
    end

    # Complete Action ----------------------------------------------------------
    # Because we know a user cannot accept his own bounty, if the current bounty
    # is accepted and the currrent user is the accepting artist, then the
    # artwork is being submitted and nothing else.
    if (@bounty.acceptor_candidacy)
      if (@bounty.acceptor_candidacy.artist == current_user)
        @bounty.completed_at = Time.now
        if @bounty.update_attributes(bounty_update_params(@bounty))
          BountyMailer.completion_email(@bounty)
          flash[:notice] = "Bounty Completed!"
          redirect_to bounty_path(@bounty)
        else
          flash[:error] = "Error completing bounty."
          logger.error "Error completing bounty #{params[:id]}: #{@bounty.inspect}; Validation errors: #{@bounty.errors.messages.inspect}"
          render 'complete'
        end
      end
    # Edit Action --------------------------------------------------------------
    else
      # If no specific artists were selected. Then create a candidacy to all
      # active artists.
      if !params[:bounty][:artist_ids] || params[:bounty][:artist_ids] == [""]
        params[:bounty][:artist_ids] =
          Artist.available().where('id <> ?', current_user.id).pluck(:id)
      end
      # Sanitize the name and description fields for bounties. Clean name of all
      # HTML, clean descs using "Relaxed" method which allows:
      #
      # "Allows an even wider variety of markup than BASIC, including images and
      # tables. Links are still limited to FTP, HTTP, HTTPS, and mailto protocols,
      # while images are limited to HTTP and HTTPS. In this mode, rel="nofollow"
      # is not added to links."
      params[:bounty][:name] = Sanitize.clean(params[:bounty][:name])
      params[:bounty][:tag_line] = Sanitize.clean(params[:bounty][:tag_line])
      params[:bounty][:description] = Sanitize.clean(params[:bounty][:description], Sanitize::Config::RELAXED)

      if @bounty.update_attributes(bounty_update_params(@bounty))
        flash[:notice] = "Bounty Updated!"
        redirect_to bounty_path(@bounty)
      else
        flash[:error] = "Error updating bounty."
        logger.error "Error updating bounty #{params[:id]}: #{@bounty.inspect}; Validation errors: #{@bounty.errors.messages.inspect}"
        render 'edit'
      end
    end
  end

  # Delete the bounty. Admins may delete any bounty. But the bounty's owner may
  # only do this if the bounty is unclaimed.
  def destroy
    @bounty = Bounty.find(params[:id])

    if (@bounty.owner == current_user && (@bounty.status == 'Unclaimed')) || current_user.admin?
      if Bounty.destroy(params[:id])
        flash[:notice] = "Bounty successfully removed!"
        redirect_to root_path
      else
        flash[:error] = "Error removing bounty."
        redirect_to root_path
      end
    else
      if @bounty.owner != current_user
        flash[:error] = "You are not authorized to remove this bounty."
        if request.env['HTTP_REFERER']
          redirect_to :back
        else
          redirect_to root_url
        end
      elsif @bounty.status == "Accepted"
        acceptor = @bounty.acceptor_candidacy.artist.get_identifier
        flash[:error] = "This bounty is being worked on by #{acceptor} and cannot be deleted."
        if request.env['HTTP_REFERER']
          redirect_to :back
        else
          redirect_to root_url
        end
      else
        flash[:error] = "This bounty is #{@bounty.status} and cannot be deleted."
        if request.env['HTTP_REFERER']
          redirect_to :back
        else
          redirect_to root_url
        end
      end
    end
  end

  private

    def bounty_create_params
      params.require(:bounty).permit(
        :name,
        :description,
        :price,
        :price_cents,
        :price_currency,
        :adult_only,
        :private,
        :complete_by,
        :tag_line,
        :mood_ids => [],
        :artist_ids => []
      )
    end

    def bounty_update_params(bounty)
      # only the acccepting artist can complete a bounty, but they can't change
      # any other bounty properties
      if bounty.acceptor_candidacy && bounty.acceptor_candidacy.artist == current_user
        return params.require(:bounty).permit(
          :preview,
          :completed_at,
          :artwork,
          :preview,
          :artwork_file_name,
          :artwork_content_type,
          :artwork_file_size,
          :artwork_updated_at,
          :preview_file_name,
          :preview_content_type,
          :preview_file_size,
          :preview_updated_at
        )
      end

      params.require(:bounty).permit(
        :name,
        :description,
        :price,
        :price_cents,
        :price_currency,
        :adult_only,
        :private,
        :complete_by,
        :tag_line,
        :mood_ids => [],
        :artist_ids => []
      )
    end
end

app/views/bounties/complete.html.erb
<div id="form-area">
  <%= semantic_form_for @bounty do |complete_form| %>
        <%=
          complete_form.input(
            :artwork,
            :as => :file,
            :required => true,
            :hint => "The completed artwork for the customer."
          )
        %>
        <%=
          complete_form.input(
            :preview,
            :as => :file,
            :required => false,
            :hint => <<-HINT
  A custom thumbnail for the completed artwork.
  Must be 200x280px. (Optional)
            HINT
          )
        %>
        <div class="control-panel">
          <%= complete_form.submit :class => "bounty-button submit-button" %>
          <%=   link_to_function 'Back', "history.back()", class: 'bounty-button' %>
        </div>
  <% end %>
</div>

app/views/bounties/edit.html.erb
<div id="form-area">
  <%= render partial: 'shared/bounty_error_messages', locals: { bounty: @bounty } %>
  <%= semantic_form_for @bounty do |bounty_form| %>
    <%=
      bounty_form.input(
        :name,
        :required => true,
        :input_html => { :size => 40 },
        :hint => "The name of your bounty."
      )
    %>
    <%=
      bounty_form.input(
        :tag_line,
        :as => :text,
        :required => true,
        :input_html => { :rows => 3, :maxlength => 160 },
        :label => "Tag Line",
        :hint => <<-HINT
A short description of your bounty for the front page. Max 160 characters.
        HINT
      )
    %>
    <%=
      render(
        :partial => 'shared/markdown_input_field',
        :locals => {
          :model => 'bounty',
          :property => 'description',
          :initial_value => @bounty.description
        }
      )
    %>
    <%=
      bounty_form.input(
        :price,
        :as => :number,
        :required => true,
        :hint => <<-HINT
The price you're willing to pay. Min $#{Bounty.MINIMUM_PRICE} USD.
        HINT
      )
    %>
    <%=
      bounty_form.input(
        :private,
        :required => false,
        :as => :select,
        :hint => <<-HINT
If a bounty is private, only the artists you pick and admins may see it.
        HINT
      )
    %>
    <%=
      bounty_form.input(
        :complete_by,
        :as => :date_select,
        :start_year => Time.now.year,
        :label => "Due Date",
        :required => false,
        :hint => "The date by which this bounty must be finished. (Optional)"
      )
    %>
    <%=
      bounty_form.input(
        :artists,
        :collection => Artist.available().where('id <> ?', current_user.id),
        :as => :check_boxes,
        :hint => "Which artists may complete your bounty?"
      )
    %>
    <%=
      bounty_form.input(
        :moods,
        :as => :check_boxes,
        :hint => <<-HINT
Tags that help describe your bounty at a glance. Min
#{Personality.MINIMUM_MOODS}. Max #{Personality.MAXIMUM_MOODS}.
        HINT
      )
    %>
    <div class="control-panel">
      <%= bounty_form.submit :class => "bounty-button submit-button" %>
      <%=   link_to_function 'Back', "history.back()", class: 'bounty-button' %>
    </div>
  <% end %>
</div>

app/views/bounties/index.html.erb
<%=
  render(
    :partial => 'shared/bounty_list',
    :locals => { :bounties => @bounties }
  )
%>

<div class='previous'>
  <%= link_to_previous_page @bounties, 'Previous', class: 'pagination' %>
</div>
<div class='next'>
  <%= link_to_next_page @bounties, 'Next', class: 'pagination' %>
</div>

<%
# dropdown menus and panels are defined here, and are attached to
# their appropriate launchers by the jQuery dropdowns plugin
%>
<div id="dropdown-filters-controls" class="dropdown dropdown-tip">
  <div class="dropdown-panel">
    <div id="filter_control">
      <%= render 'shared/filters_general' %>
      <% if current_user.is_a?(Artist) %>
        <%= render 'shared/filters_artist' %>
      <% end %>
    </div>
  </div>
</div>

app/views/bounties/new.html.erb
<div id="form-area">
  <%= render partial: 'shared/bounty_error_messages', locals: { bounty: @bounty } %>
  <%= semantic_form_for @bounty do |bounty_form| %>
    <%= bounty_form.input :name, :required => true, :input_html => { :size => 40 }, :hint => "The name of your bounty. Max 40 characters." %>
    <%= bounty_form.input :tag_line, :as => :text, :required => true, :input_html => { :rows => 3, :maxlength => 160 }, :hint => "A short description of your bounty for the front page. Max 160 characters.", :label => "Tag Line" %>
    <%=
      render(
        :partial => 'shared/markdown_input_field',
        :locals => {
          :model => 'bounty',
          :property => 'description',
          :initial_value => ''
        }
      )
    %>
    <%=
      bounty_form.input(
        :price,
        :as => :number,
        :required => true,
        :input_html => { :value => "#{Bounty.MINIMUM_PRICE}" },
        :hint => "The price you're willing to pay. Min $#{Bounty.MINIMUM_PRICE} USD."
      )
    %>
    <%=
      bounty_form.input(
        :private,
        :required => false,
        :as => :select,
        :hint => <<-HINT
If a bounty is private, only the artists you pick and admins may see it.
        HINT
      )
    %>
    <%=
      bounty_form.input(
        :complete_by,
        :as => :date_select,
        :start_year => Time.now.year,
        :label => "Due Date",
        :required => false,
        :hint => "The date by which this bounty must be finished. (Optional)"
      )
    %>
    <%=
      bounty_form.input(
        :artists,
        :collection => Artist.available().where('id <> ?', current_user.id),
        :as => :check_boxes,
        :input_html => { :checked => 'checked' },
        :hint => "Which artists may complete your bounty?"
      )
    %>
    <%=
      bounty_form.input(
        :moods,
        :as => :check_boxes,
        :hint => <<-HINT
Tags that help describe your bounty at a glance. Min
#{Personality.MINIMUM_MOODS}. Max #{Personality.MAXIMUM_MOODS}.
        HINT
      )
    %>
    <div class="control-panel">
      <%= bounty_form.submit :class => "bounty-button submit-button" %>
      <%=   link_to_function 'Back', "history.back()", class: 'bounty-button' %>
    </div>
  <% end %>
</div>

app/views/bounties/show.html.erb
<div class="name">
  <%= @bounty.name %><br>
  <% if @bounty.adult_only %>
    <div class="adult">18+</div>
  <% end %>
</div>
<% if @bounty.status == "Unclaimed" %>
  <div class="candidacies">
    <% unless @bounty.candidacies.empty? %>
      <% @bounty.candidacies.each do |c| %>
        <%= c.artist.get_identifier %>
        <% unless c == @bounty.candidacies.last %>
        or
        <% end %>
      <% end %>
      may complete this bounty for <%= humanized_money_with_symbol @bounty.price %>
    <% else %>
      All artists have rejected this bounty. :(
    <% end %>
  </div>
<% else %>
  <div class="status"><%= @bounty.status %> by <%= @bounty.acceptor_candidacy.artist.get_identifier %> for <%= humanized_money_with_symbol @bounty.price %></div>
<% end %>

<% if @bounty.status == "Completed" %>
 <img src="<%="#{@bounty.artwork.url}"%>" class="completed-art">
<% else %>
  <div class="moods">
    |
    <% @bounty.moods.each do |m| %>
      <%= m.name %> |
    <% end %>
  </div>
  <div class="bounty-desc hyphenate"><%= @bounty.description_to_html %></div>
  <%= render :partial => 'comments/list', :locals => { :comments => @bounty.comments } %>
  <% if signed_in? %>
    <%= render :partial => 'comments/new', :locals => { :bounty => @bounty } %>
  <% end %>
<% end %>
<div class="dates">
  Created on <%= @bounty.created_at.strftime("%B %d, %Y") %>
  <% if @bounty.status != "Unclaimed" %> | Accepted on <%= @bounty.acceptor_candidacy.accepted_at.strftime("%B %d, %Y") %><% end %>
  <% if @bounty.status == "Completed" %> | Completed on <%= @bounty.completed_at.strftime("%B %d, %Y") %><% end %>
  <% if @bounty.complete_by %><h3>This bounty must be finished by <%= @bounty.complete_by.strftime("%B %d, %Y") %></h3><% end %>
</div>
<div class="control-panel">
<%=   link_to_function 'Back', "history.back()", class: 'bounty-button' %>
<% if signed_in? %>
  <% if (@bounty.owner == current_user && @bounty.status == 'Unclaimed') || current_user.admin? %>
    <%=   link_to 'Update', edit_bounty_path(@bounty.id), class: 'bounty-button' %>
  <% end %>
  <% if (@bounty.owner == current_user && @bounty.status == 'Unclaimed') || current_user.admin? %>
    <%=   link_to 'Delete', @bounty, :confirm => "Are you sure you want to delete #{@bounty.name}?", :method => :delete, class: 'bounty-button' %>
  <% end %>
  <% if @bounty.artists.include?(current_user) && @bounty.status == 'Unclaimed' %>
    <%=
    link_to(
      'Accept',
      candidacy_path(
        @bounty.candidacies.find { |candidacy|
          candidacy.artist == current_user
        },
        :candidacy => {:accept => true}
      ),
      :method => :put,
      :class => 'bounty-button'
    )
    %>
  <% elsif @bounty.acceptor_candidacy &&
           @bounty.acceptor_candidacy.artist == current_user
  %>
    <%=
    link_to(
      'Un-Accept',
      candidacy_path(
        @bounty.acceptor_candidacy,
        :candidacy => {:accept => false}
      ),
      :method => :put,
      :class => 'bounty-button'
    )
    %>
  <% end %>
  <% if @bounty.artists.include?(current_user) && @bounty.status == 'Unclaimed' %>
    <%=   link_to 'Reject', candidacy_path, :method => :delete, :confirm => "Are you sure you want to reject this bounty?", class: 'bounty-button' %>
  <% end %>
  <% if @bounty.acceptor_candidacy && current_user == @bounty.acceptor_candidacy.artist && @bounty.status == 'Accepted' %>
    <%=   link_to 'Complete', complete_bounty_path(@bounty.id), class: 'bounty-button' %>
  <% end %>
  <% if @bounty.acceptor_candidacy && current_user == @bounty.acceptor_candidacy.artist && @bounty.status == 'Completed' %>
    <%=   link_to 'Update Artwork URL', edit_bounty_path(@bounty.id, "Complete"), class: 'bounty-button' %>
  <% end %>
<% end %>