config/routes.rb
Bountyboard::Application.routes.draw do

  root :to => 'Bounties#index'

  resources :artists
  resources :bounties, shallow: true do
    resources :comments
    member do
      get 'complete'
    end
  end

  # these resources are managed automatically by the system, so we don't need
  # user-accessible index, new, or edit forms
  resources :candidacies, :except => [:index, :new, :edit]
  resources :votes, :except => [:index, :new, :edit]
  resources :favorites, :except => [:index, :new, :edit]

  resources :users, :except => [:index] # forbid listing users

  # authentication routes
  match '/auth/:provider/callback', to: 'Sessions#create'
  match '/sign_out', to: 'Sessions#destroy', via: [ :delete, :post ]
  match '/auth/failure', to: 'Sessions#auth_failure'
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-wrapper">
    &copy; Devin Leonhart, Nixie Bishop, and Brent Houghton, 2013<br>
    The Bounty Board is free software available under the open source AGPL
    license.
    <a href="http://github.com/devleorepo/bountyboard">Play with the source code.</a><br>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% if signed_in? %>
    <button class="bounty-button"><%=   link_to 'Post a Bounty', new_bounty_path, id: 'post-bounty' %></button>
  <%  else %>
    <button class="persona-login-button bounty-button">Sign In to Post Your Bounty</button>
  <%  end %>
</header>

<div class="flash-box">
  <% [:notice, :error, :alert].each do |level| %>
    <% unless flash[level].blank? %>
      <div class="alert <%= flash_class(level) %>">
          <%= flash[level] %>
          <%=   link_to 'x', root_path, class: 'close' %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_nav_bar.html.erb
<nav>
  <%= link_to 'The Bounty Board', root_path %>
  <%= link_to 'Artist Profiles', artists_path %>
  <% if signed_in? && current_user.admin? %>
    <%= link_to 'New Artist', new_artist_path %>
  <% end %>
  <% if signed_in? %>
    <%= link_to 'Your Bounties', user_path(current_user.id) %>
  <% end %>
  <% if signed_in? && current_user.is_a?(Artist) %>
    <%= link_to 'Artist Dashboard', artist_path(current_user.id) %>
  <% end %>
  <a id="filters-controls-toggle" data-dropdown="#dropdown-filters-controls" href="#">
    Filter Displayed Bounties
  </a>
  <span class="login-notify-area">
    <div class="persona-buttons">
      <% if signed_in? %>
            Logged in as
        <%= current_user.get_identifier() %>
        <button class="persona-logout-button">
          Sign Out
        </button>
      <%  else %>
        <button class="persona-login-button">
          Sign In with Persona
        </button>
      <%  end %>
    </div>
    <div class="persona-ajax-spinner">
      <div class="persona-spinner-text">
        <%# The Persona login script fills in the appropriate message here. %>
      </div>
      <%= image_tag 'persona-ajax-spinner.gif' %>
    </div>
  </span>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Bounty Board</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script src="https://browserid.org/include.js" type="text/javascript"></script>
  <%= csrf_meta_tags %>

  <!-- provide HTML5 compatibility for IE 8 and older -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>
  <div class="wrapper">
  <%#    Header navigation bar on the top of the page with sign-in controls. %>

    <%= render 'layouts/nav_bar' %>

    <header>
      <% if signed_in? %>
        <button class="bounty-button"><%=   link_to 'Post a Bounty', new_bounty_path, id: 'post-bounty' %></button>
      <%  else %>
        <button class="persona-login-button bounty-button">Sign In to Post Your Bounty</button>
      <%  end %>
    </header>

    <div class="flash-box">
      <% [:notice, :error, :alert].each do |level| %>
        <% unless flash[level].blank? %>
          <div class="alert <%= flash_class(level) %>">
              <%= flash[level] %>
              <%=   link_to 'x', root_path, class: 'close' %>
          </div>
        <% end %>
      <% end %>
    </div>


  <div id="<%= "#{controller.controller_name}-#{controller.action_name}" %>" class="page-area">
    <%= yield %>
  </div>

  </div>

  <%= render 'layouts/footer' %>

</body>
</html>